# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\x12\x07predict\"\x1f\n\x0ePredictRequest\x12\r\n\x05input\x18\x01 \x03(\t\"!\n\x0fPredictResponse\x12\x0e\n\x06result\x18\x01 \x03(\t2S\n\x11PredictionService\x12>\n\x07Predict\x12\x17.predict.PredictRequest\x1a\x18.predict.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=26
  _globals['_PREDICTREQUEST']._serialized_end=57
  _globals['_PREDICTRESPONSE']._serialized_start=59
  _globals['_PREDICTRESPONSE']._serialized_end=92
  _globals['_PREDICTIONSERVICE']._serialized_start=94
  _globals['_PREDICTIONSERVICE']._serialized_end=177
# @@protoc_insertion_point(module_scope)
